# Waveforme serverless.yml
# Copyright (C) 2023 Reese Norris - All Rights Reserved

org: rnorris
app: waveforme
service: waveforme
frameworkVersion: '3'
configValidationMode: error
deprecationNotificationMode: warn:summary

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs14.x
  region: us-east-2
  stage: dev
  memorySize: 512
  architecture: arm64
  timeout: 10
  logRetentionInDays: 7

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  serve:
    handler: handler.serve
    events:
      - httpApi:
          method: GET
          path: /
      - httpApi:
          method: GET
          path: /about
      - httpApi:
          method: GET
          path: /design

custom:
  webpack:
    webpackConfig: 'webpack.config.server.js'

  serverless-offline:
    useChildProcesses: true
    noPrependStageInUrl: true
    host: 0.0.0.0
    httpPort: 3000